# SubVet GitHub Action
# Scan subdomains for takeover vulnerabilities
#
# Usage:
#   - uses: taku-tez/SubVet@v0.8
#     with:
#       subdomains: subdomains.txt
#       baseline: baseline.json  # optional
#       slack-webhook: ${{ secrets.SLACK_WEBHOOK }}  # optional

name: 'SubVet'
description: 'Scan subdomains for takeover vulnerabilities'
author: 'taku-tez'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  subdomains:
    description: 'Path to subdomains file (one per line)'
    required: true
    default: 'subdomains.txt'
  baseline:
    description: 'Path to baseline JSON file for diff mode'
    required: false
  slack-webhook:
    description: 'Slack webhook URL for notifications'
    required: false
  slack-on:
    description: 'When to notify: always, issues, new'
    required: false
    default: 'issues'
  check-ns:
    description: 'Check NS delegation'
    required: false
    default: 'true'
  check-mx:
    description: 'Check MX records'
    required: false
    default: 'true'
  check-spf:
    description: 'Check SPF includes'
    required: false
    default: 'false'
  check-srv:
    description: 'Check SRV records'
    required: false
    default: 'false'
  check-txt:
    description: 'Check TXT record references'
    required: false
    default: 'false'
  report:
    description: 'Report format (html, md, sarif). Written to report-output file.'
    required: false
  diff-json:
    description: 'Output diff as JSON (with baseline)'
    required: false
    default: 'false'
  timeout:
    description: 'Request timeout in ms'
    required: false
    default: '10000'
  concurrency:
    description: 'Number of concurrent requests'
    required: false
    default: '10'
  output:
    description: 'Output file path'
    required: false
    default: 'subvet-results.json'

outputs:
  vulnerable:
    description: 'Number of vulnerable subdomains'
    value: ${{ steps.scan.outputs.vulnerable }}
  likely:
    description: 'Number of likely vulnerable subdomains'
    value: ${{ steps.scan.outputs.likely }}
  total:
    description: 'Total subdomains scanned'
    value: ${{ steps.scan.outputs.total }}
  exit-code:
    description: 'Exit code (0=ok, 1=likely, 2=vulnerable)'
    value: ${{ steps.scan.outputs.exit-code }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build SubVet
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install
        npm run build

    - name: Run SubVet
      id: scan
      shell: bash
      env:
        INPUT_SUBDOMAINS: ${{ inputs.subdomains }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_CONCURRENCY: ${{ inputs.concurrency }}
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_CHECK_NS: ${{ inputs.check-ns }}
        INPUT_CHECK_MX: ${{ inputs.check-mx }}
        INPUT_CHECK_SPF: ${{ inputs.check-spf }}
        INPUT_CHECK_SRV: ${{ inputs.check-srv }}
        INPUT_CHECK_TXT: ${{ inputs.check-txt }}
        INPUT_REPORT: ${{ inputs.report }}
        INPUT_DIFF_JSON: ${{ inputs.diff-json }}
        INPUT_BASELINE: ${{ inputs.baseline }}
        INPUT_SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        INPUT_SLACK_ON: ${{ inputs.slack-on }}
      run: |
        # Build command as array (no eval)
        cmd=(node "$GITHUB_ACTION_PATH/dist/cli.js" scan -f "$INPUT_SUBDOMAINS")
        cmd+=(-t "$INPUT_TIMEOUT")
        cmd+=(-c "$INPUT_CONCURRENCY")
        cmd+=(-o "$INPUT_OUTPUT")
        cmd+=(--pretty -v)
        
        # Add optional flags
        if [ "$INPUT_CHECK_NS" == "true" ]; then
          cmd+=(--check-ns)
        fi
        if [ "$INPUT_CHECK_MX" == "true" ]; then
          cmd+=(--check-mx)
        fi
        if [ "$INPUT_CHECK_SPF" == "true" ]; then
          cmd+=(--check-spf)
        fi
        if [ "$INPUT_CHECK_SRV" == "true" ]; then
          cmd+=(--check-srv)
        fi
        if [ "$INPUT_CHECK_TXT" == "true" ]; then
          cmd+=(--check-txt)
        fi
        
        # Validate baseline file if specified
        if [ -n "$INPUT_BASELINE" ] && [ ! -f "$INPUT_BASELINE" ]; then
          echo "::error::Baseline file '$INPUT_BASELINE' not found. When baseline is specified, the file must exist."
          exit 1
        fi
        
        # Add diff mode if baseline exists
        if [ -n "$INPUT_BASELINE" ] && [ -f "$INPUT_BASELINE" ]; then
          cmd+=(--diff "$INPUT_BASELINE")
          if [ "$INPUT_DIFF_JSON" == "true" ]; then
            cmd+=(--diff-json)
          fi
        fi
        
        # Add report format
        if [ -n "$INPUT_REPORT" ]; then
          cmd+=(--report "$INPUT_REPORT")
        fi
        
        # Add Slack notification
        if [ -n "$INPUT_SLACK_WEBHOOK" ]; then
          cmd+=(--slack-webhook "$INPUT_SLACK_WEBHOOK" --slack-on "$INPUT_SLACK_ON")
        fi
        
        echo "Running: ${cmd[*]}"
        
        # Run and capture exit code
        set +e
        "${cmd[@]}"
        EXIT_CODE=$?
        set -e
        
        echo "exit-code=$EXIT_CODE" >> $GITHUB_OUTPUT
        
        # Parse results
        if [ -f "$INPUT_OUTPUT" ]; then
          VULNERABLE=$(jq '.summary.vulnerable' "$INPUT_OUTPUT")
          LIKELY=$(jq '.summary.likely' "$INPUT_OUTPUT")
          TOTAL=$(jq '.summary.total' "$INPUT_OUTPUT")
          
          echo "vulnerable=$VULNERABLE" >> $GITHUB_OUTPUT
          echo "likely=$LIKELY" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
        fi
        
        exit $EXIT_CODE

    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: subvet-results
        path: ${{ inputs.output }}
        retention-days: 30
